### ISSUE TITLE
Incorrectly rendering of a code snippet

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/rticles#149] opened 2018-01-08 19:20 UTC
The following code snippet 

```{r}
library(dlm)
form <- function(theta){ dlmModPoly(order = 1, dV = exp(theta[1]), dW = exp(theta[2])) }
model <- form(dlmMLE(Nile, parm = c(1, 1), form)$par)
filtered <- dlmFilter(Nile, model)
```
was rendered incorrectly using R Journal template. The following text is displayed in the generated PDF file. 
```
\begin{Schunk} \begin{Sinput} library(dlm) form <- function(theta){ dlmModPoly(order = 1, dV= exp(theta[1]), dW = exp(theta[2])) } model <- form(dlmMLE(Nile, parm = c(1, 1), form)$par) filtered<- dlmFilter(Nile, model) \end{Sinput} \end{Schunk}
```
Any ideas on what I might have done incorrectly here?

**Comment by yihui** [comment] 2018-01-09 16:15
Duplicate of #6 #10 #49 #132 etc. You didn't do anything wrong. It is our bug, which we haven't had a chance to fix yet.

**Comment by jaredhuling** [comment] 2018-03-31 20:31
Any chance to fix this? The underscore problem is making it 100% impossible to use rticles

**Comment by jaredhuling** [comment] 2018-04-02 14:04
If there is a way to grep through the resulting .tex file created after pandoc, one hack would be to insert a \\begin{verbatim}   \\end{verbatim} around calls to CodeChunk, CodeOutput in jss_article.R and then clear out the verbatims after pandoc is done.
ie
hook_chunk <- function(x, options) {
    if (output_asis(x, options)) return(x)
    paste0('\\begin{verbatim}\n\\begin{CodeChunk}\n', x, '\\end{CodeChunk}\n\\end{verbatim}')
  }
This way pandoc will properly handle the inside contents. But here I guess there is a risk of stripping out actual calls written by the user to verbatim, so maybe some unique identifier after the \\begin{verbatim} could be used, like \\begin{verbatim}%removethis\n

**Comment by jaredhuling** [comment] 2018-04-02 16:15
Does anything special need to be done to enable the prost_processor to be run? I've gotten the wrapper part to work, but the post_processor doesn't seem to be called when I put it into `jss_article()`

**Comment by yihui** [comment] 2018-04-02 16:17
@jaredhuling You need to add it to `base$post_process`: https://github.com/rstudio/rticles/blob/master/R/jss_article.R

**Comment by jaredhuling** [comment] 2018-04-02 16:21
I think what's happening is the intermediate .tex file doesn't compile and it bombs out before it gets to the post processing step.

**Comment by yihui** [comment] 2018-04-02 16:24
Also look at https://github.com/rstudio/bookdown/blob/cd2fb76f818528e/R/latex.R#L43

**Comment by yihui** [comment] 2018-07-03 16:04
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/

**Closed** 2018-07-03 16:04 UTC
