### ISSUE TITLE
Spaces in R Journal Submission Template Cannot Knit

### ISSUE THREAD

**Issue by scottschreckengaust** [rstudio/rticles#9] opened 2014-07-29 20:13 UTC
R version 3.1.1 RStudio Version 0.98.981 on Darwin 13.3.0 (OSX 10.9.4 build 13E28) appears to have problems with spaces and underscores in Rmd file names.  Creating files without spaces or underscores yields no issues.
- Example with "Untitled 2.Rmd" and "Untitled_2.Rmd":
  
  ```
  Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'RJwrapper.tex' failed.
  LaTeX errors:
  ! LaTeX Error: File `Untitled\T1\textunderscore2.tex' not found.
  
  Type X to quit or <RETURN> to proceed,
  or enter new name. (Default extension: tex)
  
  ! Emergency stop.
  <read *> 
  
   l.21   \input{Untitled\_2}
                          ^^M
  !  ==> Fatal error occurred, no output PDF file produced!
  Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> texi2dvi
  Execution halted
  ```

**Comment by englianhu** [comment] 2015-10-01 07:59
Same with me, 3 templates cannot be rendered.

```diff
> rmarkdown::draft("RyoEngAbstract.Rmd", template = "use_r_abstract", package = "rticles")
> rmarkdown::draft("RyoEngJSS.Rmd", template = "jss_article", package = "rticles")
> rmarkdown::draft("RyoEngRJournal", template = "rjournal_article", package = "rticles")
> rmarkdown::render(paste0(getwd(),'/RyoEngAbstract/RyoEngAbstract.Rmd'))

processing file: RyoEngAbstract.Rmd
  |.................................................................| 100%
  ordinary text without R code

output file: RyoEngAbstract.knit.md

/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS RyoEngAbstract.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output RyoEngAbstract.pdf --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc --template /usr/lib64/R/library/rticles/rmarkdown/templates/use_r_abstract/resources/template.tex --highlight-style tango --latex-engine pdflatex --csl /usr/lib64/R/library/rticles/rmarkdown/templates/use_r_abstract/resources/chicago-author-date.csl --bibliography bibliography.bib 
- ! LaTeX Error: File `hanging.sty' not found.
-
- Type X to quit or <RETURN> to proceed,
- or enter new name. (Default extension: sty)
- 
- Enter file name: 
- ! Emergency stop.
- <read *> 
-         
- l.4 \usepackage
- 
- pandoc: Error producing PDF from TeX source
- Error: pandoc document conversion failed with error 43
```

**Comment by jjallaire** [comment] 2015-10-01 09:42
This is because of missing LaTeX packages (you need one that provides
'hanging.sty', e.g. on Ubuntu this is the texlive-latex-extra package
on RedHat I believe it's in texlive-hanging)

**Comment by englianhu** [comment] 2015-10-02 07:19
Hi @jjallaire, sounds doesn't work on Centos7... @@"
```diff
$ sudo yum -y install texlive-latex-extra texlive-hanging
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.triple-it.nl
 * epel: mirrors.coreix.net
 * extras: centos.mirror.triple-it.nl
 * updates: centos.mirror.triple-it.nl
- No package texlive-latex-extra available.
- No package texlive-hanging available.
- Error: Nothing to do
```

**Comment by jjallaire** [comment] 2015-10-02 10:29
Centos7 has different package names for LaTeX than Ubuntu. Also on CentOS
you may need to enable additional repositories beyond the default ones
(e.g. EPEL) in order to install all the LaTeX packages you need.

**Comment by yihui** [comment] 2018-07-03 16:15
@englianhu Your issue was a completely different one. You may try TinyTeX if you don't want to waste time on looking for missing LaTeX packages again: https://yihui.name/tinytex/.

@scottschreckengaust I'm able to reproduce your issue. I'll see what I can do. In general, [spaces in file paths are not good for LaTeX](https://yihui.name/en/2018/03/space-pain/).

**Comment by yihui** [comment] 2018-07-05 15:39
@scottschreckengaust Should be fixed now. Thanks for the report!

**Closed** 2018-07-05 15:39 UTC
Labels: bug
