### ISSUE TITLE
RJournal doesn't like `^` or `%` or `$` in R code chunks

### ISSUE THREAD

**Issue by njtierney** [rstudio/rticles#70] opened 2016-05-12 02:03 UTC
Thanks for putting this package together, it's super cool!

I'm working on submitting an Article to the R Journal, and am using the R Journal template from rticles.

I've got it here on my github: https://github.com/njtierney/A-Simple-Guide-to-S3-Methods

When I render the article, I random sections of it render into text, and then the R comments get treated as first level headers. When I changed the R programming code from `^` to use `**` instead, there were fewer problems, but it now seems that when I call something like `x$residuals` in the .Rmd, LaTeX has trouble parsing it, as well as `%in%`

This is particularly on pages 4, 5, and 6 of the PDF.

I'll probably just change the .tex file to get it to render well in the end, but just thought you guys would like to know!

**Comment by yihui** [comment] 2016-05-12 04:26
Duplicate of #49 (we don't have a solution yet).

**Comment by njtierney** [comment] 2016-05-12 04:35
oops! Sorry about duplicating the issue!

**Comment by yihui** [comment] 2018-07-03 16:12
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/

**Closed** 2018-07-03 16:11 UTC
